export const STORAGE_KEYS = {
  '__FL_LK__REQUEST': '__FL_LK__REQUEST',
  '__FL_LK__REQUEST_HEADERS': '__FL_LK__REQUEST_HEADERS',
  '__FL_LK__LAST_SYNC_TIME': '__FL_LK__LAST_SYNC_TIME',
  '__FL_STORE': '__FL_STORE',
} as const